--- #YAML:1.0
name:               Params-Profile
version:            0.11
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.66
    Class::Data::Inheritable:  0.04
    Data::FormValidator:  4
    Params::Check:        0.23
    Test::More:           0.62
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
